services:
  postgres:
    image: postgres
    container_name: site-config-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: site-config-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: